services:
  - type: web
    name: the-ever-maze
    runtime: node
    buildCommand: npm install --prefix server && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: false
