services:
  - type: web
    name: the-ever-maze
    plan: free
    runtime: node
    buildCommand: npm install --include=dev --prefix client && npm install --prefix server && npm run build --prefix client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: false
