const EVENTS = {
  PLAYER_MOVE: 'PLAYER_MOVE',
  USE_GIFT: 'USE_GIFT',
  PLAYER_READY: 'PLAYER_READY',
  START_GAME: 'START_GAME',
  JOIN_ROOM: 'JOIN_ROOM',
  CREATE_ROOM: 'CREATE_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  STATE_UPDATE: 'STATE_UPDATE',
  PHASE_CHANGE: 'PHASE_CHANGE',
  LIGHT_FOUND: 'LIGHT_FOUND',
  LIGHT_TRANSFER: 'LIGHT_TRANSFER',
  LIGHT_DROPPED: 'LIGHT_DROPPED',
  GIFT_SPAWN: 'GIFT_SPAWN',
  GIFT_PICKUP: 'GIFT_PICKUP',
  TAG_EVENT: 'TAG_EVENT',
  WALL_SHIFT_WARNING: 'WALL_SHIFT_WARNING',
  WALL_SHIFT_EXECUTE: 'WALL_SHIFT_EXECUTE',
  SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
  EXIT_OPEN: 'EXIT_OPEN',
  CHANNEL_START: 'CHANNEL_START',
  CHANNEL_PROGRESS: 'CHANNEL_PROGRESS',
  CHANNEL_COMPLETE: 'CHANNEL_COMPLETE',
  MATCH_END: 'MATCH_END',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_ERROR: 'ROOM_ERROR',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  ROOM_UPDATE: 'ROOM_UPDATE',
  SWITCH_TEAM: 'SWITCH_TEAM',
  KICK_PLAYER: 'KICK_PLAYER',
  RETURN_TO_LOBBY: 'RETURN_TO_LOBBY',
  GET_PROFILE: 'GET_PROFILE'
};

const GAME_CONFIG = {
  TICK_RATE: 20,
  VISIBILITY_RADIUS: 6,
  TILE_SIZE: 32,
  TAG_RADIUS: 1.5,
  PICKUP_IMMUNITY: 2000,
  CARRIER_SPEED_MULTIPLIER: 0.9,
  CHANNEL_DURATION: 3000,
  CHANNEL_GRACE: 2000,
  WALL_SHIFT_WARNING: 3000,
  MAX_WALL_SHIFTS: 3,
  GIFT_SPAWN_INITIAL: 4,
  GIFT_SPAWN_INTERVAL: 60000,
  GIFT_SPAWN_AMOUNT: 3,
  REGIONAL_UPDATE_INTERVAL: 15000,
  WARMTH_RADIUS: 8,
  PROXIMITY_REVEAL_RADIUS: 3,
  AFK_WARNING: 45000,
  AFK_KICK: 10000,
  ROOM_TIMEOUT: 7200000,
  MATCH_DURATION: 300000,
  PHASE_3_TRIGGER: 0.7,
  SUDDEN_DEATH_DURATION: 60000,
  TAG_COOLDOWN: 3000,
  REJOIN_WINDOW: 60000,
  SMALL_MAZE: 21,
  MEDIUM_MAZE: 31,
  LARGE_MAZE: 41,
};

const TILE = { WALL: 0, FLOOR: 1, ENTRANCE_A: 2, ENTRANCE_B: 3, EXIT: 4, GATE: 5 };
const PHASE = { EXPLORE: 'EXPLORE', HUNT: 'HUNT', ESCAPE: 'ESCAPE', SUDDEN_DEATH: 'SUDDEN_DEATH' };
const TEAM = { A: 'A', B: 'B' };
const GIFT = {
  FREEZE: 'FREEZE',
  DASH: 'DASH',
  MIST: 'MIST',
  COMPASS: 'COMPASS',
  MAGIC_KEY: 'MAGIC_KEY',
  SHIELD: 'SHIELD',
  SILENT_STEPS: 'SILENT_STEPS'
};

const PLAYER_COLORS = [
  '#06b6d4', // Cyan
  '#f472b6', // Pink
  '#4ade80', // Green
  '#facc15', // Yellow
  '#f87171', // Red
  '#c084fc', // Purple
  '#fb923c', // Orange
];

const MAZE_TYPE = {
  STANDARD: 'STANDARD',
  CAVE: 'CAVE',
  ARENA: 'ARENA'
};

module.exports = {
  EVENTS: Object.freeze({
    ...EVENTS,
    CHANGE_COLOR: 'CHANGE_COLOR',
    CHANGE_MAZE_TYPE: 'CHANGE_MAZE_TYPE'
  }),
  GAME_CONFIG: Object.freeze(GAME_CONFIG),
  TILE: Object.freeze(TILE),
  PHASE: Object.freeze(PHASE),
  TEAM: Object.freeze(TEAM),
  GIFT: Object.freeze(GIFT),
  PLAYER_COLORS: Object.freeze(PLAYER_COLORS),
  MAZE_TYPE: Object.freeze(MAZE_TYPE),
};
